### ISSUE TITLE
Updated link

### ISSUE THREAD

**Issue by fayolle** [chenzhaiyu/awesome-planar-reconstruction#2]
@chenzhaiyu The paper 'Reconstruction of Convex Polytope Compositions from 3D Point-clouds' was presented at GRAPP 2021. Here is a link to the final version 
https://www.scitepress.org/Papers/2021/102971/102971.pdf 
(The arXiv link is a preprint)

A corresponding implementation can be found here 
https://github.com/mafried/csg_playground/tree/fullpipeline_polytope

**Comment by chenzhaiyu** [comment]
Thanks for the information. Links updated with 0c4cc37f95903c493d033eec4fa20808e6ec4c18.

**Comment by fayolle** [comment]
Thanks @chenzhaiyu. And thanks for the very nice collection of links.
